<!doctype html>
<html>
	<head>
		<title>Add a book</title>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
 <link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>

	</head>
	<body>
		<form action="/index.php/books/addABook" method="post">
			Title : <input type="text" name="title"></br>
			Author : <input type="text" name="author"></br>
			<input type="submit" value="Submit">
		</form>
	</body>
</html>
