<!DOCTYPE html>
<html>
	<?php $func->db;
	$book = $func->db->table('books')->find($bookId);?>
	<head>
		<title>Livre <?= ($bookId);?></title>
	</head>
	<body>
		Opérations de détails sur le livre : <?= ($book->title);?>
		<h4>Nom du livre : <?= ($book->title); ?></h4>
		<h4>Auteur du livre : <?= ($book->author); ?></h4>
		<form action="/books/<?=($bookId);?>/modify" method="get">
			<button type="submit">Modifier le livre</button>
		</form>
		<form action="/books/" method="post">
			<input name="supp" type="hidden" value="<?=$bookId?>">
			<button type="submit">Supprimer le livre</button></br>
		</form>
	</body>
</html>
