<!DOCTYPE html>
<html>
	<head>
		<title>The books</title>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	</head>
	<body>
		<form action="/index.php/books/addABook" method="get">
			<button name="add" type="submit" value="addBook">Ajouter un livre</button></br>
		</form>
	</body>
</html>
