<!DOCTYPE html>
<html>
	<?php $func->db;
	$book = $func->db->table('books')->find($bookId);?>
	<head>
		<title>Livre <?= ($bookId);?></title>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	</head>
	<body>
		Opérations de détails sur le livre : <?= ($book->title);?>
		<h4>Nom du livre : <?= ($book->title); ?></h4>
		<h4>Auteur du livre : <?= ($book->author); ?></h4>
		<form action="/index.php/books/<?=($bookId);?>/modify" method="get">
			<button type="submit">Modifier le livre</button>
		</form>
		<form action="/index.php/books/" method="post">
			<input name="supp" type="hidden" value="<?=$bookId?>">
			<button type="submit">Supprimer le livre</button></br>
		</form>
	</body>
</html>
