<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #0066ff;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 65px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Bienvenue dans votre système de gestion de bibliothèque</h1>
		<form action="/books/" method="get"><button type="submit">Voir tous les livres</button></form>
    </body>
</html>
