<!doctype html>
<html>

	<?php $func->db;
	$book = $func->db->table('books')->find($bookId);
	?>

	<head>
		<title>Modify info of book</title>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	</head>
	<body>
		<form method="post">
			Current title : <?= ($book->title); ?></br>
			New title : <input type="text" name="title"></br>
			Current author : <?= ($book->author); ?></br>
			New author : <input type="text" name="author"></br>
			<input name="id" type="hidden" value="<?=$bookId?>">
			<input type="submit" value="Submit">
		</form>
	</body>
</html>
