<!DOCTYPE html>
<html>
	<head>
		<title>Thank you</title>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	</head>
	<body>
		<h3>Vous avez entre:</h3>
		<h4>Titre : <?= ($title); ?></h4> 
		<h4>Auteur : <?= ($author); ?></h4> 
		<form action="/index.php/books/" method="get">
			<button name="Revenir au livres" type="submit">Revenir au livres</button>
		</form>
	</body>
</html>
